### ISSUE TITLE
Merge openstanding branches

### ISSUE THREAD

**Issue by paulhobbel** [BF3RM/RMBundleLoader#11] opened 2023-01-10 20:20 UTC
Right now there are some conflicts between the vodnik and skirmish branch. I also think some stuff got merged already and some did not.

Would be nice if someone can clean this up and make sure we are left again with one branch

**Comment by FoolHen** [comment] 2023-01-10 22:50
Done, closing directly

**Closed as completed** 2023-01-10 22:50 UTC

**Comment by Dumpy250** [comment] 2023-02-21 20:04
Works as intended
